[package]
name = "monitors"
version = "0.1.0"
authors = ["Matt <matttmccarthy66@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
regex = "1"
sysinfo = "0.15.0"
dirs = "1.0.5"